# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb"}

modules = ["card.py"]

doc_url = "https://fnauman.github.io/binary_classifier/"

git_url = "https://github.com/fnauman/binary_classifier/tree/{branch}/"

def custom_doc_links(name): return None
