# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"Card": "00_card.ipynb",
         "Deck": "00_deck.ipynb"}

modules = ["card.py",
           "deck.py"]

doc_url = "https://fnauman.github.io/binary_classifier/"

git_url = "https://github.com/fnauman/binary_classifier/tree/master/"

def custom_doc_links(name): return None
